### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f8727d20a40>

### ISSUE THREAD

**Issue by slflowfoon** [valentinfrlch/ha-llmvision#143]
### Bug Description
Service call for Stream Analyser fails to execute in an automation due to `PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f8727d20a40>`

LLM Vision integration won't recover unless I restart Home Assistant.

**Version**: 1.3.1

### Service Call

```yaml
action: llmvision.stream_analyzer
metadata: {}
data:
  include_filename: true
  target_width: 1920
  max_tokens: 100
  temperature: 0.4
  provider: 01JENNXWEVC67TREV6Z9FEVJK5
  message: >-
    Is there someone at the front of the house?


    Analyse the CCTV stream. If there is minimal motion or movement, reply with
    "NoMotion." Otherwise, describe any significant motion or movement. 


    If there is a person, what is the person wearing? Where are they moving to?
    Only if you can identify it's a courier, which courier is it?


    If there is a vehicle, what colour is the car? What is the registration
    plate?


    Do not describe static objects such as sitting people or parked vehicles. Do
    not describe anything that you're unsure about.


    Limit to one sentence and 120 characters
  image_entity:
    - camera.front
  expose_images: true
  model: gemini-1.5-flash
  detail: high
  duration: 10
  max_frames: 20
response_variable: geminifront
enabled: true
```

### Logs

```
2024-12-24 16:53:28.765 ERROR (MainThread) [homeassistant.components.automation.front_notification] While executing automation automation.front_notification
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 743, in async_trigger
    return await self.action_script.async_run(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        variables, trigger_context, started_action
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
    ~~~~~~~~~~~~~~~~~~~~~~^
        ex, continue_on_error, self._log_exceptions or log_exceptions
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/llmvision/__init__.py", line 305, in stream_analyzer
    client = await processor.add_streams(image_entities=call.image_entities,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                                         )
                                         ^
  File "/config/custom_components/llmvision/media_handlers.py", line 428, in add_streams
    await self.record(
    ...<6 lines>...
    )
  File "/config/custom_components/llmvision/media_handlers.py", line 220, in record
    await asyncio.gather(*(record_camera(image_entity, image_entities.index(image_entity)) for image_entity in image_entities))
  File "/config/custom_components/llmvision/media_handlers.py", line 176, in record_camera
    img = await self.hass.loop.run_in_executor(None, Image.open, io.BytesIO(frame_data))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/PIL/Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f8727d20a40>
```

**Comment by slflowfoon** [comment]
Figured out that this was due to the Blue Iris camera streams failing.
