### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by xqgex** [valentinfrlch/ha-llmvision#92]
### Bug Description
If the LLM model respond with an empty string, there are no `'candidates'` at the `'response'` object at `request_handlers.py:311`

https://github.com/valentinfrlch/ha-llmvision/blob/c304a9a0b33c70bcc096f05fc24fcb3727130efb/custom_components/llmvision/request_handlers.py#L308-L313

**Version**:  1.3.1

### Service Call

```yaml
action: llmvision.image_analyzer
data:
  remember: true
  include_filename: false
  target_width: 1280
  detail: low
  max_tokens: 100
  temperature: 0.3
  provider: AAAAAAAAAAAAAAAAAAAAAAAA
  message: >-
    Only if you see any garbage cans in this photo, phrase a message to bring
    the cans in, your response will be sent as a reminder as it is. If you don't
    see, respond with an empty string.
  image_entity:
    - camera.trash_cans_out
response_variable: response
```

### Logs

N/A

### Additional context
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/llmvision/__init__.py", line 268, in image_analyzer
    response = await client.make_request(call)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/llmvision/request_handlers.py", line 130, in make_request
    response_text = await self.google(model=model, api_key=api_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/llmvision/request_handlers.py", line 311, in google
    response_text = response.get("candidates")[0].get(
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by valentinfrlch** [comment]
This should be fixed in the latest release ([v1.3.6 release notes](https://github.com/valentinfrlch/ha-llmvision/releases/tag/v1.3.6)).
